#!/bin/sh

### BEGIN INIT INFO
# Provides: startHeadCluster
# Required-Start: $all
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop startNode
# Description: startNode
### END INIT INFO

fichName="startHeadCluster"

# Do NOT change anything below this line unless you know what you are doing!


case "$1" in
start)
	echo "Start Head Cluster"
	echo Routage eth1 vers reseau public 
	echo eth0 reseau privé
 
	sysctl -w net.ipv4.ip_forward=1
	sudo iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
	#sudo iptables -t filter -A INPUT -i lo -j ACCEPT
	#sudo iptables -t filter -A INPUT -i eth1 -p tcp -m tcp --dport 22 -j ACCEPT
	sudo iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
	
;;
install)
	$0 stop
	echo installation service
	cp $0 /etc/init.d
	update-rc.d "$fichName" defaults
	service "$fichName" start
	ps -ef | grep $0
;;
 'status')
    	log_action_msg "startNode is stopped."
   	exit 0
  ;;

stop)
	echo "Closing startNode "
	exec 1>/var/log/"$fichName".service.log 2>&1

	killall $0
;;
*)
	echo "Usage: /etc/init.d/startNode {start|stop}"
	exit 1
;;
esac

exit 0
